### ISSUE TITLE
vercel自带的域名挂了，能加一个子域名吗？

### ISSUE THREAD

**Issue by flow2000** [Kyomotoi/Project-ATRI-Docs#2]
http://project-atri-docs.vercel.app/

**Comment by Kyomotoi** [comment]
该域名正常, 请检查自身的网络环境
同时你还可以通过 `atri.imki.moe` 访问

**Comment by Kyomotoi** [comment]
貌似想表达的是 bot 帮助内的 `atri.kyomotoi.moe` 无法访问? 确实, 该域名即将弃用, 现以更换为 `atri.imki.moe`.
